### ISSUE TITLE
Move typescript types into separate files

### ISSUE THREAD

**Issue by aalykiot** [nodeshift-archived/oratrix#49]
@helio-frota so, as the project grows it's probably a good idea to refactor the code so we can have all the TS types needed into a single file for a **single source of truth** kind of thing

**Comment by helio-frota** [comment]
@alexalikiotis I think we can hold this issue a bit. And see if the project will grow properly. :+1:

**Comment by alexalikiotis** [comment]
@helio-frota sure, I just opened this for the future
