### ISSUE TITLE
develop: consolidate / simplify commands

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-archived/oratrix#74]
When running the cli with `cli add opossum` we get a JSON parse error because the `.packages.json` file
don't exists yet.

I believe that it will be good to consolidate the init command (which creates the `.package.json` file) with the add command.

```console
$ node dist/cli.js 
cli.js <command>

Commands:
  cli.js add <package>  Add new package to `.packages.json` file
  cli.js init           Initializes `.packages.json` file
  cli.js validate       Searches for mandatory package.json fields
  cli.js verify         Verifies
```

Other thing is the `validate` and the `verify`, both are "checking" things.
Maybe we need to try to improve that wording in some way.

**Comment by alexalikiotis** [comment]
@helio-frota 

- +1 about improving the wording for the commands
- when someone runs the add command we can check if a `packages.json` files exist. If not we run the init script otherwise we continue as normal

**Comment by helio-frota** [comment]
> when someone runs the add command we can check if a packages.json file exists. If not we run the init script otherwise we continue as normal (it's what NPM does)

Sounds great
